name: 🚀 Start Jenkins & Trigger CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: ☁️ Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: 🚀 Start Jenkins EC2 Instance
        run: |
          echo "Starting Jenkins EC2 instance..."
          aws ec2 start-instances --instance-ids ${{ secrets.JENKINS_INSTANCE_ID }}
          aws ec2 wait instance-running --instance-ids ${{ secrets.JENKINS_INSTANCE_ID }}

      - name: 🕒 Wait for Jenkins to boot
        run: |
          echo "Waiting for Jenkins to become available..."
          sleep 120

      - name: 🧩 Trigger Jenkins Job
        run: |
          echo "Triggering Jenkins job..."
          curl -X POST "${{ secrets.JENKINS_URL }}/job/${{ secrets.JENKINS_JOB_NAME }}/build" \
            --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}"

      - name: 🛰️ Poll Jenkins Job Status
        id: poll
        run: |
          echo "Polling Jenkins for job status..."
          for i in {1..20}; do
            STATUS=$(curl -s -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}" \
              "${{ secrets.JENKINS_URL }}/job/${{ secrets.JENKINS_JOB_NAME }}/lastBuild/api/json" | jq -r .result)
            echo "Current status: $STATUS"

            if [[ "$STATUS" != "null" ]]; then
              echo "result=$STATUS" >> $GITHUB_OUTPUT
              exit 0
            fi

            sleep 15
          done

          echo "Jenkins job timed out or never finished."
          echo "result=TIMEOUT" >> $GITHUB_OUTPUT
          exit 1

      - name: 📦 Build and Push Docker Image
        if: steps.poll.outputs.result == 'SUCCESS'
        run: |
          echo "Logging in to Docker Hub..."
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/my-app
          GIT_SHA=$(git rev-parse --short HEAD)
          TAG=${GIT_SHA:-latest}

          echo "Building Docker image..."
          docker build -t $IMAGE_NAME:$TAG .

          echo "Tagging image as 'latest' and 'previous'..."
          docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest
          docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:previous

          echo "Pushing images to Docker Hub..."
          docker push $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:previous

          echo "✅ Docker image pushed successfully."

      - name: 🔁 Rollback Docker image
        if: steps.poll.outputs.result != 'SUCCESS'
        run: |
          echo "Attempting to rollback to previous Docker image..."

          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/my-app
          FALLBACK_TAG=previous

          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

          echo "Pulling previous image: $IMAGE_NAME:$FALLBACK_TAG"
          if docker pull $IMAGE_NAME:$FALLBACK_TAG; then
            echo "Tagging as latest..."
            docker tag $IMAGE_NAME:$FALLBACK_TAG $IMAGE_NAME:latest

            echo "Pushing rollback image..."
            docker push $IMAGE_NAME:latest

            echo "✅ Rollback completed. $IMAGE_NAME:latest now points to previous stable image."
          else
            echo "⚠️ No previous image found for rollback. Skipping."
          fi

      - name: 📧 Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ steps.poll.outputs.result == 'SUCCESS' && '✅ Jenkins Job Succeeded' || '🚨 Jenkins Job Failed or Timed Out' }}
          to: anuj.107126@stu.upes.ac.in
          from: GitHub Actions <${{ secrets.EMAIL_USERNAME }}>
          body: |
            ${{ steps.poll.outputs.result == 'SUCCESS' && '🎉 The Jenkins job completed successfully.' || '❌ The Jenkins job failed or timed out.' }}

            ➤ Job: ${{ secrets.JENKINS_JOB_NAME }}
            ➤ Status: ${{ steps.poll.outputs.result }}
            ➤ Jenkins URL: ${{ secrets.JENKINS_URL }}/job/${{ secrets.JENKINS_JOB_NAME }}

      - name: 🛑 Stop EC2 after Jenkins success
        if: steps.poll.outputs.result == 'SUCCESS'
        run: |
          echo "✅ Jenkins succeeded. Stopping EC2 instance..."
          aws ec2 stop-instances --instance-ids ${{ secrets.JENKINS_INSTANCE_ID }}
