name: 🚀 Start Jenkins & Trigger CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: ☁️ Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1 # Adjust to your region (e.g., us-east-1)

      - name: 🚀 Start Jenkins EC2 Instance
        run: |
          aws ec2 start-instances --instance-ids ${{ secrets.JENKINS_INSTANCE_ID }} || { echo "Failed to start instance"; exit 1; }
          aws ec2 wait instance-running --instance-ids ${{ secrets.JENKINS_INSTANCE_ID }} || { echo "Instance failed to reach running state"; exit 1; }

      - name: 🕒 Wait for Jenkins to boot
        run: |
          echo "Waiting for Jenkins to become available..."
          until curl -s -f -o /dev/null "${{ secrets.JENKINS_URL }}/login"; do
            sleep 10
            echo "Retrying..."
          done
          echo "Jenkins is up!"

      - name: 🧩 Trigger Jenkins Job
        run: |
          curl -X POST "${{ secrets.JENKINS_URL }}/job/${{ secrets.JENKINS_JOB_NAME }}/build" \
            --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}" || { echo "Failed to trigger Jenkins job"; exit 1; }
