name: 🚀 Jenkins CI/CD with Docker & Auto-Rollback

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout Code
        uses: actions/checkout@v3

      - name: ☁️ Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: 🚀 Start Jenkins EC2 Instance
        run: |
          echo "Starting EC2..."
          aws ec2 start-instances --instance-ids ${{ secrets.JENKINS_INSTANCE_ID }}
          aws ec2 wait instance-running --instance-ids ${{ secrets.JENKINS_INSTANCE_ID }}

      - name: ⏳ Wait for Jenkins to Boot
        run: sleep 60

      - name: 🧩 Trigger Jenkins Job
        run: |
          echo "Triggering job..."
          curl -X POST "${{ secrets.JENKINS_URL }}/job/${{ secrets.JENKINS_JOB_NAME }}/build" \
            --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}"

      - name: 🛰️ Poll Jenkins Job Status
        id: poll
        run: |
          echo "Polling Jenkins for status..."
          for i in {1..20}; do
            JSON=$(curl -s -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}" \
              "${{ secrets.JENKINS_URL }}/job/${{ secrets.JENKINS_JOB_NAME }}/lastBuild/api/json")
            BUILDING=$(echo "$JSON" | jq -r .building)
            STATUS=$(echo "$JSON" | jq -r .result)
            echo "BUILDING=$BUILDING | STATUS=$STATUS"
            if [[ "$BUILDING" == "false" && "$STATUS" != "null" ]]; then
              echo "result=$STATUS" >> $GITHUB_OUTPUT
              exit 0
            fi
            sleep 15
          done
          echo "result=TIMEOUT" >> $GITHUB_OUTPUT
          exit 1

      - name: 🔐 DockerHub Login
        if: steps.poll.outputs.result == 'SUCCESS'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🐳 Build & Push Docker Image
        if: steps.poll.outputs.result == 'SUCCESS'
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/inventoware-app
          TAG=$(git rev-parse --short HEAD)
          docker build -t $IMAGE:$TAG ./invento-app
          docker tag $IMAGE:$TAG $IMAGE:latest
          docker tag $IMAGE:$TAG $IMAGE:previous
          docker push $IMAGE:$TAG
          docker push $IMAGE:latest
          docker push $IMAGE:previous

      - name: 🔁 Rollback on Failure
        if: steps.poll.outputs.result != 'SUCCESS'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🧯 Perform Rollback
        if: steps.poll.outputs.result != 'SUCCESS'
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/inventoware-app
          echo "Attempting rollback..."
          if docker pull $IMAGE:previous; then
            docker tag $IMAGE:previous $IMAGE:latest
            docker push $IMAGE:latest
            echo "Rollback successful."
          else
            echo "No previous image to roll back to."
          fi

      - name: 🛑 Stop Jenkins EC2 Instance
        if: always()
        run: |
          echo "Shutting down EC2 in 1 minute..."
          sleep 60
          aws ec2 stop-instances --instance-ids ${{ secrets.JENKINS_INSTANCE_ID }}
          aws ec2 wait instance-stopped --instance-ids ${{ secrets.JENKINS_INSTANCE_ID }}
          echo "EC2 stopped ✅"

      - name: 📧 Email Notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: |
            ${{ steps.poll.outputs.result == 'SUCCESS' && '✅ Jenkins Job Succeeded' || '🚨 Jenkins Job Failed or Timed Out' }}
          to: anuj.107126@stu.upes.ac.in
          from: GitHub Actions <${{ secrets.EMAIL_USERNAME }}>
          body: |
            ➤ Jenkins Job: ${{ secrets.JENKINS_JOB_NAME }}
            ➤ Status: ${{ steps.poll.outputs.result }}
            ➤ URL: ${{ secrets.JENKINS_URL }}/job/${{ secrets.JENKINS_JOB_NAME }}
            ➤ EC2 has been safely stopped after the job.
